# Backend services
upstream order_service {
    server order-service:8080;
    keepalive 32;
}

upstream product_service {
    server product-service:8080;
    keepalive 32;
}

upstream keycloak {
    server keycloak:8080;
    keepalive 16;
}

upstream grafana {
    server grafana:3000;
    keepalive 16;
}

upstream kafka_ui {
    server kafka-ui:8080;
    keepalive 8;
}

upstream redis_insight {
    server redis-insight:5540;
    keepalive 8;
}

upstream minio_console {
    server minio:9001;
    keepalive 8;
}

upstream minio_api {
    server minio:9000;
    keepalive 8;
}

upstream frontend {
    server frontend:3000;
    keepalive 32;
}