import type { Metadata } from "next";
import { SearchProvider } from "../../contexts/SearchContext";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { AuthProvider } from "../../providers/AuthProvider";
import { CartProvider } from "@/contexts/CartContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col container mx-auto">
        <AuthProvider>
          <SearchProvider>
            <CartProvider>
              {children}
            </CartProvider>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}