# Host и Real IP
# Передаем оригинальный Host (localhost или product-service:8080), чтобы Kestrel не блокировал запрос.
proxy_set_header Host $http_host; 
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# Жестко задаем публичные параметры (Kestrel будет использовать их для генерации ссылок, если настроен ForwardedHeadersMiddleware)
proxy_set_header X-Forwarded-Proto "https";
proxy_set_header X-Forwarded-Host "d5ddimrn36v2tdv58n65.nkhmighe.apigw.yandexcloud.net";
proxy_set_header X-Forwarded-Port "443";

# HTTP настройки
proxy_http_version 1.1;
# КРИТИЧНО: УДАЛЯЕМ эту строку! Пустой Connection ломает Kestrel.
# proxy_set_header Connection ""; 

proxy_connect_timeout 60s;
proxy_send_timeout    60s;
proxy_read_timeout    60s;
